import type { BasePrompt, Context, Injector, Rules } from './types';
import { extractSlots, fillSlot } from './slot';

// generated by sage implement

function applyInjector(template: string, injector: Injector, context: Context): { template: string; appended: string } {
    const injection = injector.fn(context);
    const slotTag = '{{' + injector.slot + '}}';

    if (template.includes(slotTag)) {
        return { template: fillSlot(template, injector.slot, injection), appended: '' };
    } else {
        return { template: template, appended: injection };
    }
}

function applyBaseRules(template: string, context: Context): string {
    let currentTemplate = template;

    const slots = extractSlots(currentTemplate);

    for (const slot of slots) {
        const slotValue = context[slot];

        if (typeof slotValue === 'string' || typeof slotValue === 'number') {
            currentTemplate = fillSlot(currentTemplate, slot, String(slotValue));
        }
    }

    return currentTemplate;
}

/**
 * Assembles a final prompt from a template, ordered injectors, and context.
 *
 * Each rule in `rules` runs in order. When `{{rule.slot}}` appears in the template,
 * the injector output replaces every occurrence inline. Otherwise the output is
 * collected and appended after context filling, separated by blank lines (`\n\n`).
 *
 * After all rules run, remaining `{{word}}` placeholders are filled from `context`
 * when the value is a string or number.
 *
 * @param basePrompt - Template string containing `{{slot}}` placeholders.
 * @param rules - Ordered injectors applied before context base fill.
 * @param context - Values for injector functions and remaining slot placeholders.
 * @returns The assembled prompt string.
 *
 * @example Sonnet / Alice / Klingon
 * ```ts
 * const basePrompt = '{{llm_spec}}, {{name}}, and {{language}}';
 * const context = { llm: 'sonnet', language: 'klingon', name: 'Alice' };
 * const llmSpec = createInjector('llm_spec', (ctx) => {
 *   switch (ctx.llm) {
 *     case 'sonnet':
 *       return 'you are a smart llm model';
 *     case 'cgpt5.5':
 *       return 'you need to be very precise';
 *     default:
 *       return 'Be precise';
 *   }
 * });
 *
 * assemble(basePrompt, [llmSpec], context);
 * // 'you are a smart llm model, Alice, and klingon'
 * ```
 */
export function assemble(basePrompt: BasePrompt, rules: Rules, context: Context): string {
    let currentTemplate = basePrompt;
    const trailingParts: string[] = [];

    for (const rule of rules) {
        const injectionResult = applyInjector(currentTemplate, rule, context);
        currentTemplate = injectionResult.template;

        if (injectionResult.appended) {
            trailingParts.push(injectionResult.appended);
        }
    }

    const filled = applyBaseRules(currentTemplate, context);

    if (trailingParts.length === 0) {
        return filled;
    }

    return filled + '\n\n' + trailingParts.join('\n\n');
}
