import type { Injector, InjectorFn } from './types';

// generated by sage implement

/**
 * Creates an injector that fills `{{slot}}` inline or appends when the slot is absent.
 *
 * @param slot - Placeholder name without braces (e.g. `'llm_spec'` for `{{llm_spec}}`).
 * @param fn - Called with `context` to produce injection text.
 * @returns An `Injector` for use in `assemble` rules.
 * @throws {TypeError} When `slot` is not a non-empty string.
 */
export function createInjector(slot: string, fn: InjectorFn): Injector {
    if (typeof slot !== 'string' || slot.trim() === '') {
        throw new TypeError('slot must be a non-empty string');
    }
    return { slot, fn };
}
