// generated by sage implement

/**
 * Replaces every `{{slot}}` occurrence in `template` with `content`.
 */
export function fillSlot(template: string, slot: string, content: string): string {
    const escapedSlot = slot.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const pattern = new RegExp(`\\{\\{${escapedSlot}\\}\\}`, 'g');
    return template.replace(pattern, content);
}

/**
 * Returns unique `{{word}}` slot names from `template` in first-seen order.
 */
export function extractSlots(template: string): string[] {
    const slotNames: string[] = [];
    const seenSlots: string[] = [];
    const regex = /\{\{(\w+)\}\}/g;
    let match: RegExpExecArray | null;

    while ((match = regex.exec(template)) !== null) {
        const slotName = match[1];

        if (!seenSlots.includes(slotName)) {
            seenSlots.push(slotName);
            slotNames.push(slotName);
        }
    }

    return slotNames;
}
